spring:
  profiles:
    include:
      - db
      - common

---

spring:
  config:
    activate:
      on-profile: db

  datasource:
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
---

spring:
  config:
    activate:
      on-profile: common

  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

---

spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mariadb://localhost:3306/web

  jpa:
    generate-ddl: true
